// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azxgurhmktbxiygyiraq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6eGd1cmhta3RieGl5Z3lpcmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MDU0MzIsImV4cCI6MjA1NDE4MTQzMn0.7ayr59C4wsW-EMC5FeK6wtbmRGL2P8umI9xbgOi2L1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);